name: Builds

on:
  push:
    branches: master
    paths:
      - Makefile
      - 'src/**'
      - '.github/workflows/build_tests.yaml'
  pull_request:
    branches: master
    paths:
      - Makefile
      - 'src/**'
      - '.github/workflows/build_tests.yaml'

jobs:
  # GitHub Currently only supports running directly on Ubuntu,
  # for any other Linux we need to use a container.

  rocky-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ 'rockylinux:8', 'rockylinux:9']

    container:
      image: ${{ matrix.os }}

    steps:
      - name: Install tools/deps
        run: dnf -y install gcc make

      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: make
        run: CFLAGS=-Werror make V=1

  debian:
    runs-on: ubuntu-latest

    container:
      image: debian:12

    steps:
      - name: Install deps
        run: |
          apt-get -y update
          apt-get -y install gcc make

      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: make
        run: CFLAGS=-Werror make V=1

  # Alpine Linux with musl libc and GCC
  alpine:
    runs-on: ubuntu-latest

    container:
      image: alpine:edge

    strategy:
      fail-fast: false
      matrix:
        compiler: [ 'gcc', 'clang' ]

    steps:
      - name: Install tools/deps
        run: apk add build-base ${{ matrix.compiler }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: make CC=${{ matrix.compiler }}
        run: CFLAGS=-Werror make CC=${{ matrix.compiler }} V=1

  fedora:
    runs-on: ubuntu-latest

    container:
      image: fedora:latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [ 'gcc', 'clang' ]

    steps:
      - name: Install tools/deps
        run: dnf -y install ${{ matrix.compiler }} make

      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: make CC=${{ matrix.compiler }}
        run: CFLAGS=-Werror make CC=${{ matrix.compiler }} V=1
